### ISSUE TITLE
Extraneous character in binary data

### ISSUE THREAD

**Issue by amigrave** [JohnAD/bson#4]
Hi John,

I'm trying to send some data from python to nim using [bson](https://github.com/py-bson/bson) and I have a strange behavior.

Here's an example of python code to generate the bson:

```python
with open("/tmp/test", "wb") as f: 
    f.write(bson.dumps({  
        'buffer': b'GET / HTTP/1.0\r\nHost: test.my.127.0.0.1.xip.io\r\n\r\n', 
    }))
```
```python
bson.loads(open("/tmp/test", "rb").read())                                                                                    
# Out[3]: {'buffer': b'GET / HTTP/1.0\r\nHost: test.my.127.0.0.1.xip.io\r\n\r\n'}
```

here's the nim code to unserialize:

```nim
import bson, strutils
var doc = newBsonDocument(readFile("/tmp/test"))
echo doc["buffer"].bytes
echo doc["buffer"].bytes.toHex
```

and the output:

```
2GET / HTTP/1.0
Host: test.my.127.0.0.1.xip.io


3200000000474554202F20485454502F312E300D0A486F73743A20746573742E6D792E3132372E302E302E312E7869702E696F0D0A0D0A
```

Here's the payload generated by python's bson:
```
00000000  44 00 00 00 05 62 75 66  66 65 72 00 32 00 00 00  |D....buffer.2...|
00000010  00 47 45 54 20 2f 20 48  54 54 50 2f 31 2e 30 0d  |.GET / HTTP/1.0.|
00000020  0a 48 6f 73 74 3a 20 74  65 73 74 2e 6d 79 2e 31  |.Host: test.my.1|
00000030  32 37 2e 30 2e 30 2e 31  2e 78 69 70 2e 69 6f 0d  |27.0.0.1.xip.io.|
00000040  0a 0d 0a 00                                       |....|
```

I don't know the bson spec but it seems nim bson includes the size of the binary data into the decoded data itself,  eg:

`ABCD`
```
ABCD
040000000041424344
```

`ABCDE`:
```
ABCDE
05000000004142434445
```

`ABCDEF`
```
ABCDEF
0600000000414243444546
```

Meanwhile I use this as a workaround :)
```nim
doc["buffer"].bytes[5..^1]
```

**Comment by tuffnatty** [comment]
Yes, the `bytes` method outputs binary BSON, which we have to parse ourselves when there is no other way to get the content (e.g. regex) as the corresponding object fields are private.
Fortunately in your case (string) there is a built-in converter:
```nim
var s: string = doc["buffer"]
```

**Comment by JohnAD** [comment]
For reference: the converter is called `toString` and can be invoked directly:

```nim
var s = doc["buffer"].toString
```

Technically, the reference to the documentation is at [`toString`](https://github.com/JohnAD/bson/blob/master/docs/bson-ref.rst#tostring), but as you can see the doc for that entry is mostly empty.

So, a note to myself: flush out documentation for the converters.

**Comment by amigrave** [comment]
Thanks both for your answer.

Maybe I'm doing something wrong but casting to string either implicitly or explicitly result in this form:
```
{"$bindata": "R0VUIC8gSFRYnJpY29sZ [...] hOTIzZjkyZDQ0Yg0KDQo="}
```

which is not not what I want either. Do I miss something ?

**Comment by tuffnatty** [comment]
You generated this BSON by passing a Python `bytes` value, which resulted in storing it as a BSON Binary type. Use `str`, e.g. `buffer.decode()` to get normal UTF-8 string in BSON. Or, if you really need it as Binary, you have to use `bytes` on the field and manually remove first 4 and last 1 byte from the result - as of the current state of `bson` API.

**Comment by amigrave** [comment]
I need it as binary indeed so I'll keep the workaround of striping out extraneous bytes, thanks !

**Comment by JohnAD** [comment]
@amigrave  that looks like the mongodb extended JSON representation of a binary string.

https://docs.mongodb.com/manual/reference/mongodb-extended-json/

Mind posting the BSON doc file? (or the hex equivalent). I'd like to make sure the library isn't broken somewhere.

**Comment by JohnAD** [comment]
I was able to recreate what @amigrave saw by running the python script.

I'm investigating; should hear from me in the next day or so.

**Comment by JohnAD** [comment]
Proper solution found. @amigrave 's code would work correctly as:

```nim
import bson, strutils
var doc = newBsonDocument(readFile("/tmp/test"))
echo doc["buffer"].binstr
```

https://github.com/JohnAD/bson/blob/master/docs/bson-ref.rst#binstr

But, again, I need to improve the documentation. I think I'll write up a separate page explaining the functions for converting to/from the binary subtypes.

**Comment by amigrave** [comment]
Thanks @JohnAD !
